title: Paul O. Lewis Lab Home
email: paul.lewis@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the web site of Paul O. Lewis, Department of Ecology and Evolutionary Biology, University of Connecticut, Storrs, CT. USA.
baseurl: "" # the subpath of your site, e.g. /blog

header_pages:
   - about.md
   - publications.md
   - software.md
   - people.md
   - teaching.md

url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: polewis
github_username:  plewis

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
